---
- name: Provision Ubuntu
  hosts: localhost
  gather_facts: false

  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    gh_token: "{{ lookup('env', 'GH_TOKEN') }}"

  tasks:
    - name: Include apt tasks
      include_tasks: tasks/apt.yml
      tags: apt

    - name: Include docker tasks
      include_tasks: tasks/docker.yml
      tags: docker

    - name: Include ssh tasks
      include_tasks: tasks/ssh.yml
      tags: ssh

    - name: Include tools tasks
      include_tasks: tasks/tools.yml
      tags: tools

    - name: Include zsh tasks
      include_tasks: tasks/zsh.yml
      tags: zsh

    - name: Include dotfiles tasks
      include_tasks: tasks/dotfiles.yml
      tags: dotfiles

    - name: Include rust tasks
      include_tasks: tasks/rust.yml
      tags: rust

    - name: Include neovim tasks
      include_tasks: tasks/neovim.yml
      tags: neovim

    - name: Include go tasks
      include_tasks: tasks/go.yml
      tags: go

    - name: Include js tasks
      include_tasks: tasks/js.yml
      tags: js

    - name: Include python tasks
      include_tasks: tasks/python.yml
      tags: python

    - name: Include terraform tasks
      include_tasks: tasks/terraform.yml
      tags: terraform


    - name: Include Kubernetes tasks
      include_tasks: tasks/kubernetes.yml
      tags: k8s

    - name: Include zk tasks
      include_tasks: tasks/zk.yml
      tags: zk

    - name: Include ai tasks
      include_tasks: tasks/ai.yml
      tags: ai
