---
- name: Provision Ubuntu
  hosts: all
  gather_facts: false

  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    gh_token: "{{ lookup('env', 'GH_TOKEN') }}"

  tasks:
    - name: Include apt tasks
      include_tasks: tasks/apt.yml
      tags: apt

    - name: Include ssh tasks
      include_tasks: tasks/ssh.yml
      tags: ssh

    - name: Include tools tasks
      include_tasks: tasks/tools.yml
      tags: tools

    - name: Include zsh tasks
      include_tasks: tasks/zsh.yml
      tags: zsh

    - name: Include dotfiles tasks
      include_tasks: tasks/dotfiles.yml
      tags: dotfiles

    - name: Include neovim tasks
      include_tasks: tasks/neovim.yml
      tags: neovim

    - name: Include go tasks
      include_tasks: tasks/go.yml
      tags: go

    - name: Include docker tasks
      include_tasks: tasks/docker.yml
      tags: docker

    - name: Include terraform tasks
      include_tasks: tasks/terraform.yml
      tags: terraform

    - name: Include fonts tasks
      include_tasks: tasks/fonts.yml
      tags: fonts

    - name: Include vscode tasks
      include_tasks: tasks/vscode.yml
      tags: vscode

    - name: Include rust tasks
      include_tasks: tasks/rust.yml
      tags: rust

    - name: Include Kubernetes tasks
      include_tasks: tasks/kubernetes.yml
      tags: k8s
