---
- name: Run apt update & upgrade
  apt:
    update_cache: yes
    upgrade: yes
  become: true
  tags: apt

- name: Install core packages
  apt:
    name:
      - git
      - wget
      - curl
      - cmake
      - build-essential
  become: true
  tags: apt
