---
- name: Run apt update & upgrade
  apt:
    update_cache: yes
    upgrade: yes
  become: true
  tags: apt

- name: Install core packages
  apt:
    name:
      - git
      - curl
      - cmake
      - build-essential
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libxml2-dev

  become: true
  tags: apt
