---
- name: Run apt update & upgrade
  apt:
    update_cache: yes
    upgrade: yes
  become: true
  tags: apt

- name: Install core packages
  apt:
    name:
      - git
      - wget
      - curl
  become: true
  tags: apt

- name: Install useful dev packages
  apt:
    name:
      - cmake
      - build-essential
      - pkg-config
      - libssl-dev
  become: true
  tags: apt
