---
- name: Check if JetBrains dir exists
  shell: ls /usr/share/fonts/jetbrains
  register: jetbrains_check
  changed_when: false
  ignore_errors: true
  tags: fonts

- name: Check if Maple dir exists
  shell: ls /usr/share/fonts/maple
  register: maple_check
  changed_when: false
  ignore_errors: true
  tags: fonts

- name: Create JetBrains fonts directory
  file:
    path: /usr/share/fonts/jetbrains
    state: directory
  when: jetbrains_check.rc != 0
  become: true
  tags: fonts

- name: Create Maple fonts directory
  file:
    path: /usr/share/fonts/maple
    state: directory
  when: maple_check.rc != 0
  become: true
  tags: fonts

- name: Register pwd
  shell: pwd
  register: pwd
  changed_when: false
  tags: fonts

- name: Copy JetBrains fonts to system
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/jetbrains
    mode: 0644
  with_fileglob:
    - "{{ pwd.stdout }}/fonts/jetbrains/*"
  become: true
  tags: fonts

- name: Copy Maple fonts to system
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/maple
    mode: 0644
  with_fileglob:
    - "{{ pwd.stdout }}/fonts/maple/*"
  become: true
  tags: fonts

- name: Update font cache
  shell: fc-cache -f -v
  ignore_errors: true
  become: true
  tags: fonts
