---
- name: Remove existing Go install
  command: rm -rf /usr/local/go
  become: true
  tags: go

- name: Get Go version
  shell: curl -s https://go.dev/VERSION\?m=text | awk 'NR==1'
  register: go_version
  tags: go

- name: Download and extract Go
  shell: |
    wget "https://dl.google.com/go/{{ go_version.stdout }}.linux-amd64.tar.gz"
    tar -C /usr/local -xzf go*.tar.gz
    rm ./go*.tar.gz
  become: true
  tags: go

- name: Install Go tools
  shell: |
    export PATH="/usr/local/go/bin:$PATH"
    go install github.com/google/pprof@latest
    go install github.com/jesseduffield/lazydocker@latest
    go install github.com/jesseduffield/lazygit@latest
    go install github.com/xxxserxxx/gotop/v4/cmd/gotop@latest
    go install github.com/charmbracelet/gum@latest
    go install github.com/maaslalani/nap@main
    go install github.com/go-delve/delve/cmd/dlv@latest
    go install github.com/cosmtrek/air@latest
    go install github.com/merschformann/gotz@latest
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
    go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
    go install github.com/charmbracelet/glow@latest
    go install github.com/zricethezav/gitleaks/v8@latest
  tags: go
