---
- name: Install Bun
  shell: curl -fsSL https://bun.sh/install | bash
  become: true
  tags: js

- name: Install ppm
  shell: curl -fsSL https://get.pnpm.io/install.sh | sh -
  become: true
  tags: js
