---
- name: Check if nvim is already installed
  shell: nvim --version
  register: nvim_check
  changed_when: false
  failed_when: nvim_check.rc == 0
  ignore_errors: true
  tags: neovim

- name: Clone neovim repo
  git:
    repo: https://github.com/neovim/neovim
    dest: /home/{{ ansible_user }}/local/neovim
    version: stable
  tags: neovim
  when: nvim_check.rc != 0

- name: Install neovim dependencies
  apt:
    name:
      - cmake
      - ninja-build
      - gettext
      - unzip
    state: present
  become: true
  tags: neovim
  when: nvim_check.rc != 0

- name: Build & install neovim
  shell: |
    cd /home/{{ ansible_user }}/local/neovim
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    git checkout stable
    sudo make install
  tags: neovim
  when: nvim_check.rc != 0

- name: Install post neovim dependencies
  apt:
    name:
      - python3.8-venv # required by mason to install pip packages
    state: present
  become: true
  ignore_errors: true
  tags: neovim

- name: Install neovim plugins
  shell: nvim --headless "+Lazy! sync" +qa
  tags: neovim
