---
- name: Check if rust is already installed
  shell: cargo --version
  ignore_errors: true
  register: cargo_check
  failed_when: cargo_check.rc == 0
  changed_when: false
  tags: rust

- name: Install Rust
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    export PATH="$HOME/.cargo/bin:$PATH"
  environment:
    HOME: "/home/{{ ansible_user }}"
  become: true
  become_user: "{{ ansible_user }}"
  tags: rust
  when: cargo_check.rc != 0

- name: Install Rust tools
  shell: |
    export PATH="$HOME/.cargo/bin:$PATH"
    cargo install xh
    cargo install dust
    cargo install --locked bat
    cargo install --locked zoxide
    cargo install git-delta
    cargo install exa
    cargo install fnm
    cargo install hurl
    cargo install csvlens
  tags: rust

- name: Install Alacritty
  shell: |
    export PATH="$HOME/.cargo/bin:$PATH"
    cargo install alacritty
  tags: rust
