---
- name: Install ssh-keygen package
  apt:
    name:
      - openssh-client
    state: present
  become: true
  tags: ssh

- name: Create ~/.ssh for user
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"
  changed_when: false
  tags: ssh

- name: Check if SSH key exists
  stat:
    path: /home/{{ ansible_user }}/.ssh/id_rsa
  register: ssh_key_stat
  tags: ssh

- name: Generate SSH key pair
  become_user: "{{ ansible_user }}"
  command: ssh-keygen -t rsa -b 4096 -f /home/{{ ansible_user }}/.ssh/id_rsa -q -N ""
  tags: ssh
  when: ssh_key_stat.stat.exists == False

- name: Debug - Print GH_TOKEN
  debug:
    var: lookup('env', 'GH_TK')
  tags: ssh

- name: Get hostname
  command: hostname
  register: hostname_result
  tags: ssh

- name: Add public key to GitHub
  uri:
    url: https://api.github.com/user/keys
    method: POST
    body_format: json
    headers:
      Accept: application/vnd.github+json
      Authorization: "Bearer {{ lookup('env', 'GH_TK') }}"
      X-GitHub-Api-Version: 2022-11-28
    body: '{"title":"{{ ansible_user }}@{{ hostname_result.stdout }}","key":"{{ lookup(''file'', ''/home/{{ ansible_user }}/.ssh/id_rsa.pub'') }}"'
    status_code: 201
  become: true
  become_user: "{{ ansible_user }}"
  register: github_response
  tags: ssh

- name: Add github.com to known_hosts
  shell: ssh-keyscan -H github.com >> /home/{{ ansible_user }}/.ssh/known_hosts
  tags: ssh
  become: true
