---
- name: Run apt update & upgrade
  apt:
    update_cache: yes
    upgrade: yes
  become: true
  tags: apt

- name: Install core packages
  apt:
    name:
      - git
      - curl
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
  become: true
  tags: apt

- name: Install workflow tools
  apt:
    name:
      - stow
      - zsh
      - tmux
      - ripgrep
      - fd-find
      - jq
      - zoxide
    state: present
  tags: apt

- name: Install fzf
  shell: |
    git clone --depth 1 https://github.com/junegunn/fzf.git /home/{{ ansible_user }}/.fzf
    yes | bash /home/{{ ansible_user}}/.fzf/install
  become: true
  become_user: "{{ ansible_user }}"
  register: fzf_output
  tags: apt

- name: Print fzf output
  debug:
    var: fzf_output.stdout_lines
  tags: apt
