---
- name: Run apt update & upgrade
  apt:
    update_cache: yes
    upgrade: yes
  become: true
  tags: apt

- name: Install core packages
  apt:
    name:
      - git
      - curl
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3.8-venv
  become: true
  tags: apt
