---
- name: Provision Ubuntu
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Install aws cli
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install
        rm -r aws
      become: true

