---
- name: Clone dotfiles
  git:
    repo: git@github.com:celsobenedetti/dotfiles.git
    dest: /home/{{ ansible_user }}/.dotfiles/
    version: main
  tags: dotfiles

- name: Clone zk notes
  git:
    repo: git@github.com:celsobenedetti/zk.git
    dest: /home/{{ ansible_user }}/Documents/notes
    version: main
  tags: dotfiles

- name: Install GNU Stow
  apt:
    name: stow
    state: present
  become: true
  tags: dotfiles

- name: Unlink existing dotfiles
  command: stow -v -d /home/{{ ansible_user }}/.dotfiles -t /home/{{ ansible_user }} -R .
  args:
    chdir: /home/{{ ansible_user }}/.dotfiles
  tags: dotfiles

- name: Remove zshrc
  file:
    path: /home/{{ ansible_user }}/.zshrc
    state: absent
  tags: dotfiles

- name: Link dotfiles
  command: stow tmux zsh git vscode alacritty zk
  args:
    chdir: /home/{{ ansible_user }}/.dotfiles
  tags: dotfiles
