---
- name: Check if nvim is already installed
  shell: nvim --version
  register: nvim_check
  changed_when: false
  ignore_errors: true
  tags: neovim

- name: Clone neovim repo
  git:
    repo: https://github.com/neovim/neovim
    dest: /home/{{ ansible_user }}/local/neovim
    version: stable
  tags: neovim
  when: nvim_check.rc != 0

- name: Install neovim dependencies
  apt:
    name:
      - cmake
      - ninja-build
      - gettext
      - unzip
    state: present
  become: true
  tags: neovim
  when: nvim_check.rc != 0

- name: Build & install neovim
  shell: |
    cd /home/{{ ansible_user }}/local/neovim
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    git checkout stable
    sudo make install
  tags: neovim
  when: nvim_check.rc != 0

- name: Clone neovim config files
  git:
    repo: git@github.com:celsobenedetti/nvim.git
    dest: /home/{{ ansible_user }}/.config/nvim
    version: main
  tags: neovim

- name: Install neovim plugins
  shell: nvim --headless "+Lazy! sync" +qa
  tags: neovim
