---
- name: Install ssh-keygen package
  apt:
    name:
      - openssh-client
    state: present
  tags: ssh-key

- name: Check if SSH key exists
  stat:
    path: ~/.ssh/id_rsa
  register: ssh_key_stat
  become: yes
  become_user: "{{ ansible_user }}"
  tags: ssh-key

- name: Generate SSH key pair
  shell: |
    ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -q -N ""
  become: yes
  become_user: "{{ ansible_user }}"
  tags: ssh-key
  when: ssh_key_stat.stat.exists == False

- name: Add public key to GitHub
  uri:
    url: https://api.github.com/user/keys
    method: POST
    body_format: json
    headers:
      Accept: application/vnd.github+json
      Authorization: "Bearer {{ lookup('env', 'GH_TK') }}"
      X-GitHub-Api-Version: 2022-11-28

    body: '{"title":"ansible-provisined-ubuntu","key":"{{ lookup(''file'', ''~/.ssh/id_rsa.pub'') }}"'
    status_code: 201
  become: yes
  become_user: "{{ ansible_user }}"
  register: github_response
  tags: ssh-key

- name: Add github.com to known_hosts
  shell: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
  tags: ssh-key
