---
- name: Install workflow tools
  apt:
    name:
      - tmux
      - ripgrep
      - fd-find
      - jq
      - zoxide
      - direnv
    state: present
  become: true
  tags: tools

- name: Install fzf
  shell: |
    git clone --depth 1 https://github.com/junegunn/fzf.git /home/{{ ansible_user }}/.fzf
    yes | bash /home/{{ ansible_user}}/.fzf/install
  register: fzf_output
  tags: tools

- name: Print fzf output
  debug:
    var: fzf_output.stdout_lines
  tags: tools

- name: Get GitHub CLI sources
  shell: |
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  become: true
  tags: tools

- name: Install GitHub CLI
  apt:
    name: gh
    state: present
    update_cache: yes
  become: true
  tags: tools
