---
- name: Install zsh
  apt:
    name:
      - zsh
    state: present
  become: true
  tags: zsh

- name: Install Oh My Zsh
  shell: |
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh > install.sh
    sh install.sh --unattended
    rm install.sh
  tags: zsh

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags: zsh

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  tags: zsh

- name: Install powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
  tags: zsh

- name: Install zsh-wakatime
  git:
    repo: https://github.com/wbingli/zsh-wakatime.git
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-wakatime
  tags: zsh

- name: Remove zshrc
  file:
    path: /home/{{ ansible_user }}/.zshrc
    state: absent
  tags: zsh
