---
- name: Install extra apps
  hosts: all
  gather_facts: false

  tasks:
    - name: Run apt update & upgrade
      apt:
        update_cache: yes
        upgrade: yes
      become: true
      tags: apt

    - name: Install core packages
      apt:
        name:
          - timeshift
          - qbittorrent
          - vlc
      become: true
      tags: apt
