---
- name: Install Sway related software
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Run apt update & upgrade
      apt:
        update_cache: yes
        upgrade: yes
      become: true

    - name: Install dependencies
      apt:
        name:
          - sway
          - grim # screenshot
          - slurp # screenshot selection
          - xfg-desktop-portal-wlr # xfg-desktop-portal backend used for screensharing
          - wofi # application launcher
      become: true

    - name: Install pip deps
      pip:
        name:
          - stacki3
        state: present
