---
- name: Install virtualization tools
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install virtualbox

      apt:
        name: virtualbox
        update_cache: yes
      become: true
      tags: virtual-machines

    - name: Check if Vagrant is installed
      stat:
        path: /usr/bin/vagrant
      register: vagrant_installed
      tags: virtual-machines

    - name: Add Vagrant repository
      shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      become: true
      tags: virtual-machines
      when: vagrant_installed.stat.exists == False

    - name: Install vagrant
      apt:
        name: vagrant
        update_cache: yes
      become: true
      tags: virtual-machines
